import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Footer from './component/Footer';
import Header from './component/Header';
import HeaderMo from './component/HeaderMo';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-w-[375px]'>
        <Header />
        <HeaderMo />
        <div className='max-w-[1440px] mx-auto mt-[72px] max-768:min-w-[375px] max-md:mt-[56px]'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
